version: '3.8'

services:
  votiface:
    build: .
    container_name: votiface-facerecog
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python --version

  django-api:
    build: .
    container_name: votiface-django-api
    working_dir: /app/votiface_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
